### ISSUE TITLE
Python Typing enforcement

### ISSUE THREAD

**Issue by ArmandBriere** [ArmandBriere/Archy#11]
Since we are using python typing to improve code quality, it would be good to have `tox` notifying developers when typing is missing

 Pylint or maybe some other python module could provide that

Example:

```py
def hello(name):
    return f"Hello {name}"
```

This code should look like this:

```py
def hello(name: str) -> str:
    return f"Hello {name}"
```

**Comment by CmD0** [comment]
Pylint has this idea as an issue that is marked as a WIP but isn't implemented yet, [mypy](http://mypy-lang.org/) seems to be a good option as it transitions methods to be statically typed and adds compile time type checks. if @PierreOlivierBrillant is still working on it, could be a good thing to look into. Otherwise I can start looking into implementing this.

**Comment by PierreOlivierBrillant** [comment]
Please do :)
